[2024-12-30T21:04:16.861+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-30T21:04:16.878+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_weather.fetch_and_publish_weather manual__2024-12-30T21:04:15.639300+00:00 [queued]>
[2024-12-30T21:04:16.886+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_weather.fetch_and_publish_weather manual__2024-12-30T21:04:15.639300+00:00 [queued]>
[2024-12-30T21:04:16.887+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-30T21:04:16.898+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): fetch_and_publish_weather> on 2024-12-30 21:04:15.639300+00:00
[2024-12-30T21:04:16.906+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=664) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-30T21:04:16.908+0000] {standard_task_runner.py:72} INFO - Started process 666 to run task
[2024-12-30T21:04:16.908+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'test_weather', 'fetch_and_publish_weather', 'manual__2024-12-30T21:04:15.639300+00:00', '--job-id', '829', '--raw', '--subdir', 'DAGS_FOLDER/test_weather.py', '--cfg-path', '/tmp/tmp_058frng']
[2024-12-30T21:04:16.909+0000] {standard_task_runner.py:105} INFO - Job 829: Subtask fetch_and_publish_weather
[2024-12-30T21:04:16.948+0000] {task_command.py:467} INFO - Running <TaskInstance: test_weather.fetch_and_publish_weather manual__2024-12-30T21:04:15.639300+00:00 [running]> on host 865c783184f2
[2024-12-30T21:04:17.023+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_weather' AIRFLOW_CTX_TASK_ID='fetch_and_publish_weather' AIRFLOW_CTX_EXECUTION_DATE='2024-12-30T21:04:15.639300+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-30T21:04:15.639300+00:00'
[2024-12-30T21:04:17.024+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-30T21:05:17.033+0000] {logging_mixin.py:190} INFO - Error publishing to Kafka: KafkaTimeoutError: Failed to update metadata after 60.0 secs.
[2024-12-30T21:05:17.034+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-30T21:05:17.044+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-30T21:05:17.044+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=test_weather, task_id=fetch_and_publish_weather, run_id=manual__2024-12-30T21:04:15.639300+00:00, execution_date=20241230T210415, start_date=20241230T210416, end_date=20241230T210517
[2024-12-30T21:05:17.098+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-30T21:05:17.111+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-30T21:05:17.113+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
