[2024-12-30T19:57:19.028+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-30T19:57:19.043+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: kafka_to_mongo.consume_from_kafka_and_store_in_mongo manual__2024-12-30T19:57:15.118798+00:00 [queued]>
[2024-12-30T19:57:19.051+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: kafka_to_mongo.consume_from_kafka_and_store_in_mongo manual__2024-12-30T19:57:15.118798+00:00 [queued]>
[2024-12-30T19:57:19.051+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-30T19:57:19.063+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): consume_from_kafka_and_store_in_mongo> on 2024-12-30 19:57:15.118798+00:00
[2024-12-30T19:57:19.072+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=632) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-30T19:57:19.074+0000] {standard_task_runner.py:72} INFO - Started process 633 to run task
[2024-12-30T19:57:19.074+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'kafka_to_mongo', 'consume_from_kafka_and_store_in_mongo', 'manual__2024-12-30T19:57:15.118798+00:00', '--job-id', '115', '--raw', '--subdir', 'DAGS_FOLDER/kafka_to_mongo.py', '--cfg-path', '/tmp/tmpcfc07z10']
[2024-12-30T19:57:19.076+0000] {standard_task_runner.py:105} INFO - Job 115: Subtask consume_from_kafka_and_store_in_mongo
[2024-12-30T19:57:19.119+0000] {task_command.py:467} INFO - Running <TaskInstance: kafka_to_mongo.consume_from_kafka_and_store_in_mongo manual__2024-12-30T19:57:15.118798+00:00 [running]> on host f4979116b9f3
[2024-12-30T19:57:19.187+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='kafka_to_mongo' AIRFLOW_CTX_TASK_ID='consume_from_kafka_and_store_in_mongo' AIRFLOW_CTX_EXECUTION_DATE='2024-12-30T19:57:15.118798+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-30T19:57:15.118798+00:00'
[2024-12-30T19:57:19.188+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-30T19:57:19.204+0000] {conn.py:362} INFO - <BrokerConnection node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.26.0.8', 9092)]>: connecting to kafka:9092 [('172.26.0.8', 9092) IPv4]
[2024-12-30T19:57:19.205+0000] {conn.py:957} INFO - Probing node bootstrap-0 broker version
[2024-12-30T19:57:19.206+0000] {conn.py:393} INFO - <BrokerConnection node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.26.0.8', 9092)]>: Connection complete.
[2024-12-30T19:57:19.311+0000] {conn.py:1019} INFO - Broker version identified as 2.6.0
[2024-12-30T19:57:19.312+0000] {conn.py:1020} INFO - Set configuration api_version=(2, 6, 0) to skip auto check_version requests on startup
[2024-12-30T19:57:19.313+0000] {consumer.py:122} WARNING - group_id is None: disabling auto-commit.
[2024-12-30T19:57:19.313+0000] {subscription_state.py:167} INFO - Updating subscribed topics to: ('my_topic',)
[2024-12-30T19:57:19.335+0000] {subscription_state.py:253} INFO - Updated partition assignment: [('my_topic', 0)]
[2024-12-30T19:57:19.337+0000] {conn.py:362} INFO - <BrokerConnection node_id=1 host=kafka:9092 <connecting> [IPv4 ('172.26.0.8', 9092)]>: connecting to kafka:9092 [('172.26.0.8', 9092) IPv4]
[2024-12-30T19:57:19.337+0000] {conn.py:393} INFO - <BrokerConnection node_id=1 host=kafka:9092 <connecting> [IPv4 ('172.26.0.8', 9092)]>: Connection complete.
[2024-12-30T19:57:19.338+0000] {conn.py:673} INFO - <BrokerConnection node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.26.0.8', 9092)]>: Closing connection. 
[2024-12-30T20:22:12.554+0000] {fetcher.py:847} INFO - Fetch offset 1 is out of range for topic-partition ('my_topic', 0)
[2024-12-30T20:49:44.520+0000] {conn.py:850} ERROR - <BrokerConnection node_id=1 host=kafka:9092 <connected> [IPv4 ('172.26.0.8', 9092)]>: socket disconnected
[2024-12-30T20:49:44.524+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1 host=kafka:9092 <connected> [IPv4 ('172.26.0.8', 9092)]>: Closing connection. KafkaConnectionError: socket disconnected
[2024-12-30T20:49:44.525+0000] {client_async.py:330} WARNING - Node 1 connection failed -- refreshing metadata
[2024-12-30T20:49:44.526+0000] {future.py:77} ERROR - Fetch to node 1 failed: KafkaConnectionError: socket disconnected
[2024-12-30T20:49:44.528+0000] {conn.py:362} INFO - <BrokerConnection node_id=1 host=kafka:9092 <connecting> [IPv4 ('172.26.0.8', 9092)]>: connecting to kafka:9092 [('172.26.0.8', 9092) IPv4]
[2024-12-30T20:49:44.529+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1 host=kafka:9092 <connecting> [IPv4 ('172.26.0.8', 9092)]> returned error 111. Disconnecting.
[2024-12-30T20:49:44.530+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1 host=kafka:9092 <connecting> [IPv4 ('172.26.0.8', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-12-30T20:49:44.531+0000] {client_async.py:330} WARNING - Node 1 connection failed -- refreshing metadata
[2024-12-30T20:49:44.685+0000] {conn.py:362} INFO - <BrokerConnection node_id=1 host=kafka:9092 <connecting> [IPv4 ('172.26.0.8', 9092)]>: connecting to kafka:9092 [('172.26.0.8', 9092) IPv4]
[2024-12-30T20:49:44.686+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1 host=kafka:9092 <connecting> [IPv4 ('172.26.0.8', 9092)]> returned error 111. Disconnecting.
[2024-12-30T20:49:44.688+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1 host=kafka:9092 <connecting> [IPv4 ('172.26.0.8', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-12-30T20:49:44.689+0000] {client_async.py:330} WARNING - Node 1 connection failed -- refreshing metadata
[2024-12-30T20:49:44.893+0000] {conn.py:362} INFO - <BrokerConnection node_id=1 host=kafka:9092 <connecting> [IPv4 ('172.26.0.8', 9092)]>: connecting to kafka:9092 [('172.26.0.8', 9092) IPv4]
[2024-12-30T20:49:44.894+0000] {conn.py:402} ERROR - Connect attempt to <BrokerConnection node_id=1 host=kafka:9092 <connecting> [IPv4 ('172.26.0.8', 9092)]> returned error 111. Disconnecting.
[2024-12-30T20:49:44.895+0000] {conn.py:673} ERROR - <BrokerConnection node_id=1 host=kafka:9092 <connecting> [IPv4 ('172.26.0.8', 9092)]>: Closing connection. KafkaConnectionError: 111 ECONNREFUSED
[2024-12-30T20:49:44.896+0000] {client_async.py:330} WARNING - Node 1 connection failed -- refreshing metadata
[2024-12-30T20:49:45.302+0000] {conn.py:362} INFO - <BrokerConnection node_id=1 host=kafka:9092 <connecting> [IPv4 ('172.26.0.8', 9092)]>: connecting to kafka:9092 [('172.26.0.8', 9092) IPv4]
