[2024-12-30T19:59:26.167+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-30T19:59:26.182+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_kafka_producer.fetch_and_publish_weather scheduled__2024-12-30T19:59:20+00:00 [queued]>
[2024-12-30T19:59:26.189+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_kafka_producer.fetch_and_publish_weather scheduled__2024-12-30T19:59:20+00:00 [queued]>
[2024-12-30T19:59:26.190+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-30T19:59:26.203+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): fetch_and_publish_weather> on 2024-12-30 19:59:20+00:00
[2024-12-30T19:59:26.211+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=779) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-30T19:59:26.213+0000] {standard_task_runner.py:72} INFO - Started process 781 to run task
[2024-12-30T19:59:26.214+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather_kafka_producer', 'fetch_and_publish_weather', 'scheduled__2024-12-30T19:59:20+00:00', '--job-id', '144', '--raw', '--subdir', 'DAGS_FOLDER/weather_kafka_producer.py', '--cfg-path', '/tmp/tmp1iax8s2t']
[2024-12-30T19:59:26.215+0000] {standard_task_runner.py:105} INFO - Job 144: Subtask fetch_and_publish_weather
[2024-12-30T19:59:26.255+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_kafka_producer.fetch_and_publish_weather scheduled__2024-12-30T19:59:20+00:00 [running]> on host f4979116b9f3
[2024-12-30T19:59:26.336+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_kafka_producer' AIRFLOW_CTX_TASK_ID='fetch_and_publish_weather' AIRFLOW_CTX_EXECUTION_DATE='2024-12-30T19:59:20+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-30T19:59:20+00:00'
[2024-12-30T19:59:26.337+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-30T20:00:26.486+0000] {logging_mixin.py:190} INFO - Error publishing to Kafka: KafkaTimeoutError: Failed to update metadata after 60.0 secs.
[2024-12-30T20:00:26.489+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-30T20:00:26.511+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-30T20:00:26.513+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=weather_kafka_producer, task_id=fetch_and_publish_weather, run_id=scheduled__2024-12-30T19:59:20+00:00, execution_date=20241230T195920, start_date=20241230T195926, end_date=20241230T200026
[2024-12-30T20:00:26.576+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-30T20:00:26.593+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-30T20:00:26.596+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
