[2024-12-30T20:53:03.966+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-30T20:53:03.981+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_kafka_producer.fetch_and_publish_weather scheduled__2024-12-30T20:52:55+00:00 [queued]>
[2024-12-30T20:53:03.988+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_kafka_producer.fetch_and_publish_weather scheduled__2024-12-30T20:52:55+00:00 [queued]>
[2024-12-30T20:53:03.989+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-30T20:53:04.000+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): fetch_and_publish_weather> on 2024-12-30 20:52:55+00:00
[2024-12-30T20:53:04.008+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=154) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-30T20:53:04.009+0000] {standard_task_runner.py:72} INFO - Started process 156 to run task
[2024-12-30T20:53:04.010+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather_kafka_producer', 'fetch_and_publish_weather', 'scheduled__2024-12-30T20:52:55+00:00', '--job-id', '739', '--raw', '--subdir', 'DAGS_FOLDER/weather_kafka_producer.py', '--cfg-path', '/tmp/tmpkyb2_te0']
[2024-12-30T20:53:04.011+0000] {standard_task_runner.py:105} INFO - Job 739: Subtask fetch_and_publish_weather
[2024-12-30T20:53:04.052+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_kafka_producer.fetch_and_publish_weather scheduled__2024-12-30T20:52:55+00:00 [running]> on host 865c783184f2
[2024-12-30T20:53:04.126+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_kafka_producer' AIRFLOW_CTX_TASK_ID='fetch_and_publish_weather' AIRFLOW_CTX_EXECUTION_DATE='2024-12-30T20:52:55+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-30T20:52:55+00:00'
[2024-12-30T20:53:04.127+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-30T20:54:04.278+0000] {logging_mixin.py:190} INFO - Error publishing to Kafka: KafkaTimeoutError: Failed to update metadata after 60.0 secs.
[2024-12-30T20:54:04.279+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-30T20:54:04.288+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-30T20:54:04.289+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=weather_kafka_producer, task_id=fetch_and_publish_weather, run_id=scheduled__2024-12-30T20:52:55+00:00, execution_date=20241230T205255, start_date=20241230T205303, end_date=20241230T205404
[2024-12-30T20:54:04.335+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-30T20:54:04.349+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-30T20:54:04.351+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
