[2024-12-30T20:12:22.543+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-30T20:12:22.558+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_kafka_producer.fetch_and_publish_weather manual__2024-12-30T20:12:21.485242+00:00 [queued]>
[2024-12-30T20:12:22.565+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_kafka_producer.fetch_and_publish_weather manual__2024-12-30T20:12:21.485242+00:00 [queued]>
[2024-12-30T20:12:22.566+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-30T20:12:22.578+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): fetch_and_publish_weather> on 2024-12-30 20:12:21.485242+00:00
[2024-12-30T20:12:22.586+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1428) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-30T20:12:22.588+0000] {standard_task_runner.py:72} INFO - Started process 1430 to run task
[2024-12-30T20:12:22.589+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather_kafka_producer', 'fetch_and_publish_weather', 'manual__2024-12-30T20:12:21.485242+00:00', '--job-id', '264', '--raw', '--subdir', 'DAGS_FOLDER/weather_kafka_producer.py', '--cfg-path', '/tmp/tmpchva6ce2']
[2024-12-30T20:12:22.590+0000] {standard_task_runner.py:105} INFO - Job 264: Subtask fetch_and_publish_weather
[2024-12-30T20:12:22.638+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_kafka_producer.fetch_and_publish_weather manual__2024-12-30T20:12:21.485242+00:00 [running]> on host f4979116b9f3
[2024-12-30T20:12:22.734+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_kafka_producer' AIRFLOW_CTX_TASK_ID='fetch_and_publish_weather' AIRFLOW_CTX_EXECUTION_DATE='2024-12-30T20:12:21.485242+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-30T20:12:21.485242+00:00'
[2024-12-30T20:12:22.735+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-30T20:13:22.897+0000] {logging_mixin.py:190} INFO - Error publishing to Kafka: KafkaTimeoutError: Failed to update metadata after 60.0 secs.
[2024-12-30T20:13:22.898+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-30T20:13:22.907+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-30T20:13:22.908+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=weather_kafka_producer, task_id=fetch_and_publish_weather, run_id=manual__2024-12-30T20:12:21.485242+00:00, execution_date=20241230T201221, start_date=20241230T201222, end_date=20241230T201322
[2024-12-30T20:13:22.943+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-30T20:13:22.956+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-30T20:13:22.958+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
