[2024-12-30T20:38:58.700+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-30T20:38:58.724+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_kafka_producer.fetch_and_publish_weather scheduled__2024-12-30T20:38:50+00:00 [queued]>
[2024-12-30T20:38:58.736+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_kafka_producer.fetch_and_publish_weather scheduled__2024-12-30T20:38:50+00:00 [queued]>
[2024-12-30T20:38:58.738+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-30T20:38:58.757+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): fetch_and_publish_weather> on 2024-12-30 20:38:50+00:00
[2024-12-30T20:38:58.765+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=3139) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-30T20:38:58.768+0000] {standard_task_runner.py:72} INFO - Started process 3141 to run task
[2024-12-30T20:38:58.768+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather_kafka_producer', 'fetch_and_publish_weather', 'scheduled__2024-12-30T20:38:50+00:00', '--job-id', '593', '--raw', '--subdir', 'DAGS_FOLDER/weather_kafka_producer.py', '--cfg-path', '/tmp/tmpanfheo63']
[2024-12-30T20:38:58.769+0000] {standard_task_runner.py:105} INFO - Job 593: Subtask fetch_and_publish_weather
[2024-12-30T20:38:58.813+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_kafka_producer.fetch_and_publish_weather scheduled__2024-12-30T20:38:50+00:00 [running]> on host f4979116b9f3
[2024-12-30T20:38:58.898+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_kafka_producer' AIRFLOW_CTX_TASK_ID='fetch_and_publish_weather' AIRFLOW_CTX_EXECUTION_DATE='2024-12-30T20:38:50+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-30T20:38:50+00:00'
[2024-12-30T20:38:58.899+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-30T20:39:59.113+0000] {logging_mixin.py:190} INFO - Error publishing to Kafka: KafkaTimeoutError: Failed to update metadata after 60.0 secs.
[2024-12-30T20:39:59.114+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-30T20:39:59.126+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-30T20:39:59.127+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=weather_kafka_producer, task_id=fetch_and_publish_weather, run_id=scheduled__2024-12-30T20:38:50+00:00, execution_date=20241230T203850, start_date=20241230T203858, end_date=20241230T203959
[2024-12-30T20:39:59.148+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-30T20:39:59.161+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-30T20:39:59.163+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
