[2024-12-30T20:26:45.976+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-30T20:26:45.990+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_kafka_producer.fetch_and_publish_weather scheduled__2024-12-30T20:26:40+00:00 [queued]>
[2024-12-30T20:26:45.999+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_kafka_producer.fetch_and_publish_weather scheduled__2024-12-30T20:26:40+00:00 [queued]>
[2024-12-30T20:26:45.999+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-30T20:26:46.013+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): fetch_and_publish_weather> on 2024-12-30 20:26:40+00:00
[2024-12-30T20:26:46.022+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2375) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-30T20:26:46.024+0000] {standard_task_runner.py:72} INFO - Started process 2377 to run task
[2024-12-30T20:26:46.024+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather_kafka_producer', 'fetch_and_publish_weather', 'scheduled__2024-12-30T20:26:40+00:00', '--job-id', '452', '--raw', '--subdir', 'DAGS_FOLDER/weather_kafka_producer.py', '--cfg-path', '/tmp/tmp0j6eq2zj']
[2024-12-30T20:26:46.025+0000] {standard_task_runner.py:105} INFO - Job 452: Subtask fetch_and_publish_weather
[2024-12-30T20:26:46.066+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_kafka_producer.fetch_and_publish_weather scheduled__2024-12-30T20:26:40+00:00 [running]> on host f4979116b9f3
[2024-12-30T20:26:46.134+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_kafka_producer' AIRFLOW_CTX_TASK_ID='fetch_and_publish_weather' AIRFLOW_CTX_EXECUTION_DATE='2024-12-30T20:26:40+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-30T20:26:40+00:00'
[2024-12-30T20:26:46.135+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-30T20:27:46.342+0000] {logging_mixin.py:190} INFO - Error publishing to Kafka: KafkaTimeoutError: Failed to update metadata after 60.0 secs.
[2024-12-30T20:27:46.343+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-30T20:27:46.352+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-30T20:27:46.352+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=weather_kafka_producer, task_id=fetch_and_publish_weather, run_id=scheduled__2024-12-30T20:26:40+00:00, execution_date=20241230T202640, start_date=20241230T202645, end_date=20241230T202746
[2024-12-30T20:27:46.384+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-30T20:27:46.397+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-30T20:27:46.399+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
