[2024-12-30T20:47:51.642+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-30T20:47:51.656+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_kafka_producer.fetch_and_publish_weather scheduled__2024-12-30T20:47:45+00:00 [queued]>
[2024-12-30T20:47:51.662+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_kafka_producer.fetch_and_publish_weather scheduled__2024-12-30T20:47:45+00:00 [queued]>
[2024-12-30T20:47:51.663+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-30T20:47:51.673+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): fetch_and_publish_weather> on 2024-12-30 20:47:45+00:00
[2024-12-30T20:47:51.680+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=3762) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-12-30T20:47:51.682+0000] {standard_task_runner.py:72} INFO - Started process 3764 to run task
[2024-12-30T20:47:51.682+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather_kafka_producer', 'fetch_and_publish_weather', 'scheduled__2024-12-30T20:47:45+00:00', '--job-id', '707', '--raw', '--subdir', 'DAGS_FOLDER/weather_kafka_producer.py', '--cfg-path', '/tmp/tmp__c47fpc']
[2024-12-30T20:47:51.684+0000] {standard_task_runner.py:105} INFO - Job 707: Subtask fetch_and_publish_weather
[2024-12-30T20:47:51.724+0000] {task_command.py:467} INFO - Running <TaskInstance: weather_kafka_producer.fetch_and_publish_weather scheduled__2024-12-30T20:47:45+00:00 [running]> on host f4979116b9f3
[2024-12-30T20:47:51.791+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_kafka_producer' AIRFLOW_CTX_TASK_ID='fetch_and_publish_weather' AIRFLOW_CTX_EXECUTION_DATE='2024-12-30T20:47:45+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-30T20:47:45+00:00'
[2024-12-30T20:47:51.792+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-30T20:48:51.996+0000] {logging_mixin.py:190} INFO - Error publishing to Kafka: KafkaTimeoutError: Failed to update metadata after 60.0 secs.
[2024-12-30T20:48:51.997+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-12-30T20:48:52.007+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-30T20:48:52.008+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=weather_kafka_producer, task_id=fetch_and_publish_weather, run_id=scheduled__2024-12-30T20:47:45+00:00, execution_date=20241230T204745, start_date=20241230T204751, end_date=20241230T204852
[2024-12-30T20:48:52.039+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-12-30T20:48:52.052+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-30T20:48:52.054+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
